apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-pvc
  namespace: s3-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: s3-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: s3-identity-service:latest
        ports:
        - containerPort: 7851
        env:
        - name: DB_PATH
          value: "/data/identity.db"
        volumeMounts:
        - mountPath: /data
          name: identity-storage
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /health
            port: 7851
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7851
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: identity-storage
        persistentVolumeClaim:
          claimName: identity-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: s3-storage
spec:
  selector:
    app: identity-service
  ports:
  - port: 7851
    targetPort: 7851
    protocol: TCP
  type: ClusterIP