apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
  namespace: s3-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
      - name: metadata-service
        image: s3-metadata-service:latest
        ports:
        - containerPort: 7891
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgresql-service:5432/s3_metadata"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 7891
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7891
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  namespace: s3-storage
spec:
  selector:
    app: metadata-service
  ports:
  - port: 7891
    targetPort: 7891
    protocol: TCP
  type: ClusterIP