apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-service
  namespace: s3-storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: object-service
  template:
    metadata:
      labels:
        app: object-service
    spec:
      containers:
      - name: object-service
        image: s3-object-service:latest
        ports:
        - containerPort: 7871
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 7871
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7871
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: object-service
  namespace: s3-storage
spec:
  selector:
    app: object-service
  ports:
  - port: 7871
    targetPort: 7871
    protocol: TCP
  type: ClusterIP