apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  namespace: s3-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-service
  namespace: s3-storage
spec:
  serviceName: storage-service
  replicas: 3
  selector:
    matchLabels:
      app: storage-service
  template:
    metadata:
      labels:
        app: storage-service
    spec:
      containers:
      - name: storage-service
        image: s3-storage-service:latest
        ports:
        - containerPort: 7881
        env:
        - name: STORAGE_ROOT
          value: "/data/storage"
        - name: DB_PATH
          value: "/data/storage.db"
        volumeMounts:
        - mountPath: /data
          name: storage-data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 7881
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7881
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: storage-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Gi

---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: s3-storage
spec:
  selector:
    app: storage-service
  ports:
  - port: 7881
    targetPort: 7881
    protocol: TCP
  type: ClusterIP