rate_limiter:
  algorithm: "sliding_window_counter"
  max_requests: 5
  algorithms:
    fixed_window:
      window_size: 5000
    sliding_window_counter:
      window_size: 1000
      precision: 100
      cleanup_interval: 1000
      overlap_factor: 0.6
    sliding_window_log:
      window_size: 5000
      precision: 1000
      overlap_factor: 0.5
    token_bucket:
      refill_rate: 1
    leaky_bucket:
      leak_rate: 10
  redis:
    host: "localhost"
    port: 6379 