apiVersion: v1
kind: Pod
metadata:
  name: kvdb-test-pod
  namespace: distributed-db
  labels:
    app: kvdb-test
spec:
  containers:
  - name: test-runner
    image: kvdb-test:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "tail -f /dev/null"]  # Keep pod running
    ports:
    - containerPort: 8080
    env:
    - name: PYTHONPATH
      value: "/app"
    - name: CONFIG_FILE
      value: "config.yaml"
    workingDir: /app
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m" 