# Database Configuration
database:
  # Persistent port for the database node
  persistent_port: 55201
  
  # Default DB port (0 = auto-assign)
  db_port: 8080

# Node Configuration
node:
  node_id: "distributed-database-0"
  host: "0.0.0.0"
  http_port: 8080

# Cluster Configuration
cluster:
  # Seed nodes configuration with ID and port
  seed_nodes:
    - id: "distributed-database-0"
      host: "distributed-database-0.db-headless-service.distributed-db.svc.cluster.local"
      http_port: 8080
      db_port: 8080
      persistent_port: 55201
      gossip_port: 25101      # Port for RobustHashingGossipNode
      failure_detection_port: 35101  # Port for failure detection server
      anti_entropy_port: 55301       # http_port + 300 (changed from +200 to avoid conflict)
      monitoring_port: 55401         # http_port + 400
    - id: "distributed-database-1"
      host: "distributed-database-1.db-headless-service.distributed-db.svc.cluster.local"
      http_port: 8080
      db_port: 8080
      persistent_port: 55202
      gossip_port: 25102      # Port for RobustHashingGossipNode
      failure_detection_port: 35102  # Port for failure detection server
      anti_entropy_port: 55302       # http_port + 300 (changed from +200 to avoid conflict)
      monitoring_port: 55402         # http_port + 400
    - id: "distributed-database-2"
      host: "distributed-database-2.db-headless-service.distributed-db.svc.cluster.local"
      http_port: 8080
      db_port: 8080
      persistent_port: 55203
      gossip_port: 25103      # Port for RobustHashingGossipNode
      failure_detection_port: 35103  # Port for failure detection server
      anti_entropy_port: 55303       # http_port + 300 (changed from +200 to avoid conflict)
      monitoring_port: 55403         # http_port + 400
  
  replication_factor: 3

# Consistency Settings
consistency:
  default_read: "ONE"
  default_write: "ONE"

# Timing Configuration
timing:
  failure_check_interval: 2.0
  failure_threshold: 3
  anti_entropy_interval: 30.0

# Data Storage
storage:
  data_dir: "/data/{node_id}"  # {node_id} will be replaced with actual node ID

# Logging
logging:
  level: "INFO"

# Monitoring
monitoring:
  enabled: true
  health_check_port: 8081 