apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: rate-limiter
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
        command: ["redis-server", "--bind", "0.0.0.0"]
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
      nodeSelector:
        app: redis
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "redis"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: rate-limiter
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP 