apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: rate-limiter
spec:
  containers:
  - name: test-container
    image: python:3.9-slim
    command: ["/bin/sh", "-c"]
    args:
    - |
      apt-get update && apt-get install -y curl && \
      pip install aiohttp requests && \
      mkdir -p /tests && \
      cd /tests && \
      echo "Waiting for test files to be mounted..." && \
      while [ ! -f /tests/test_eks_fixed_window.py ]; do sleep 1; done && \
      echo "Test files mounted, starting tests..." && \
      python3 test_eks_fixed_window.py && \
      python3 test_eks_rate_limiter.py && \
      python3 test_eks_sliding_window_log.py && \
      python3 test_eks_sliding_window_counter.py
    volumeMounts:
    - name: test-files
      mountPath: /tests
  volumes:
  - name: test-files
    configMap:
      name: test-files
      defaultMode: 0755 