apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: distributed-db
  labels:
    app: distributed-database
spec:
  selector:
    app: distributed-database
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: health
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: db-headless-service
  namespace: distributed-db
  labels:
    app: distributed-database
spec:
  selector:
    app: distributed-database
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: internal
      port: 9080
      targetPort: 9080
      protocol: TCP
  clusterIP: None  # Headless service for internal cluster communication

---
apiVersion: v1
kind: Service
metadata:
  name: db-external-service
  namespace: distributed-db
  labels:
    app: distributed-database
spec:
  selector:
    app: distributed-database
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  type: NodePort  # For external access in local clusters