apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: proximity-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: proximity/api-gateway:latest
        ports:
        - containerPort: 7891
          name: http
        - containerPort: 7892
          name: grpc
        env:
        - name: REDIS_HOST
          value: "redis-cache-0.redis-cache.proximity-service.svc.cluster.local"
        - name: REDIS_PORT
          value: "6739"
        - name: LOCATION_SERVICE_URL
          value: "http://location-service:8921"
        - name: BUSINESS_SERVICE_URL
          value: "http://business-service:9823"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 7891
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7891
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: proximity-service
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: 7891
  - name: grpc
    port: 7892
    targetPort: 7892