apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: proximity-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
      - name: location-service
        image: proximity/location-service:latest
        ports:
        - containerPort: 8921
          name: http
        - containerPort: 8922
          name: metrics
        env:
        - name: REDIS_HOST
          value: "redis-cache-0.redis-cache.proximity-service.svc.cluster.local"
        - name: REDIS_PORT
          value: "6739"
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8921
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8921
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: proximity-service
spec:
  selector:
    app: location-service
  ports:
  - name: http
    port: 8921
    targetPort: 8921
  - name: metrics
    port: 8922
    targetPort: 8922