apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: proximity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9290
          name: prometheus
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: proximity-service
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway:7891']
      
      - job_name: 'location-service'
        static_configs:
          - targets: ['location-service:8922']
      
      - job_name: 'business-service'
        static_configs:
          - targets: ['business-service:9824']
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: proximity-service
spec:
  selector:
    app: prometheus
  ports:
  - port: 9290
    targetPort: 9290